# Generated by Django 5.0.1 on 2024-01-11 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Card_number', models.IntegerField()),
                ('Cvv', models.IntegerField()),
                ('Expiry_date', models.DateField()),
                ('Time_stamp', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('Total', models.FloatField()),
                ('Status', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email_id', models.EmailField(max_length=254)),
                ('Phone_no', models.BigIntegerField()),
                ('Timestamp', models.TimeField()),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Email_id', models.EmailField(max_length=254)),
                ('Phone_no', models.BigIntegerField()),
                ('Password', models.IntegerField()),
                ('Status', models.CharField(choices=[('0', 'Inactive'), ('1', 'Active')], max_length=25)),
                ('Address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=25)),
                ('Rent_per_day', models.CharField(max_length=20)),
                ('Product_color', models.CharField(max_length=20)),
                ('Product_size', models.CharField(max_length=20)),
                ('Product_description', models.TextField()),
                ('image', models.ImageField(upload_to='photos')),
                ('Status', models.CharField(choices=[('1', 'Available'), ('0', 'Not Available')], max_length=25)),
                ('Category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('Payment_mode', models.CharField(max_length=25)),
                ('Address', models.CharField(max_length=100)),
                ('Total', models.FloatField()),
                ('Start_date', models.DateField()),
                ('End_date', models.DateField()),
                ('Status', models.CharField(choices=[('1', 'Confirm'), ('0', 'Pending')], max_length=25)),
                ('Cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.cart')),
                ('Product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.product')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='Product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.product'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.FloatField()),
                ('Payment_date', models.DateField()),
                ('Status', models.CharField(choices=[('1', 'Unpaid'), ('0', 'Paid')], max_length=20)),
                ('Card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.card')),
                ('Order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.order')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.IntegerField()),
                ('Comment', models.TextField()),
                ('Timestamp', models.TimeField()),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Complain_details', models.TextField()),
                ('Subject', models.CharField(max_length=50)),
                ('Status', models.CharField(choices=[('1', 'Unsolved'), ('0', 'Solved')], max_length=20)),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='User_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.user'),
        ),
        migrations.AddField(
            model_name='card',
            name='User_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.user'),
        ),
    ]
