# Generated by Django 5.0.1 on 2024-02-01 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Status',
            field=models.CharField(choices=[('0', 'Pending'), ('1', 'Confirm')], max_length=25),
        ),
        migrations.AlterField(
            model_name='product',
            name='Status',
            field=models.CharField(choices=[('0', 'Not Available'), ('1', 'Available')], max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='Status',
            field=models.CharField(choices=[('1', 'Active'), ('0', 'Inactive')], max_length=25),
        ),
    ]
