# Generated by Django 5.0.1 on 2024-02-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_alter_product_status_sub_cat_product_sub_cat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Status',
            field=models.CharField(choices=[('0', 'Paid'), ('1', 'Unpaid')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='Status',
            field=models.CharField(choices=[('0', 'Inactive'), ('1', 'Active')], max_length=25),
        ),
    ]
