# Generated by Django 5.0 on 2024-02-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_alter_payment_status_alter_user_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Rent_per_day',
            new_name='Rent',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Sub_cat_id',
            new_name='Sub_Category_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='Status',
            field=models.CharField(choices=[('1', 'Confirm'), ('0', 'Pending')], max_length=25),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Status',
            field=models.CharField(choices=[('1', 'Unpaid'), ('0', 'Paid')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='Status',
            field=models.CharField(choices=[('1', 'Active'), ('0', 'Inactive')], max_length=25),
        ),
    ]
