# Generated by Django 5.0 on 2024-02-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0006_alter_order_status_alter_product_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Status',
            field=models.CharField(choices=[('0', 'Paid'), ('1', 'Unpaid')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='Password',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='Status',
            field=models.CharField(choices=[('1', 'Active'), ('0', 'Inactive')], max_length=25),
        ),
    ]
