# Generated by Django 5.0 on 2024-02-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0009_alter_order_status_alter_product_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='Status',
            field=models.CharField(choices=[('0', 'Solved'), ('1', 'Unsolved')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Status',
            field=models.CharField(choices=[('1', 'Unpaid'), ('0', 'Paid')], max_length=20),
        ),
    ]
