# Generated by Django 5.0 on 2024-02-27 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0011_alter_cart_status_alter_complain_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='Status',
            field=models.CharField(choices=[('Unsolved', 'Unsolved'), ('Solved', 'Solved')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='Status',
            field=models.CharField(choices=[('Confirm', 'Confirm'), ('Pending', 'Pending')], max_length=25),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='Status',
            field=models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='Status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=25),
        ),
    ]
