# Generated by Django 5.0 on 2024-02-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0012_alter_complain_status_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='Name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='Time_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='Status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirm', 'Confirm')], max_length=25),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='Timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='Status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirm', 'Confirm')], max_length=25),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Payment_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Status',
            field=models.CharField(choices=[('Not Available', 'Not Available'), ('Available', 'Available')], max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='Status',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active')], max_length=25),
        ),
    ]
