# Generated by Django 5.0 on 2024-02-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0013_inquiry_name_alter_card_time_stamp_alter_cart_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiry',
            old_name='Email_id',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='inquiry',
            old_name='Phone_no',
            new_name='Phone',
        ),
        migrations.AlterField(
            model_name='complain',
            name='Status',
            field=models.CharField(choices=[('Solved', 'Solved'), ('Unsolved', 'Unsolved')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='Status',
            field=models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='Status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=25),
        ),
    ]
