# Generated by Django 5.0 on 2024-03-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0014_rename_email_id_inquiry_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Cart_id',
        ),
        migrations.AlterField(
            model_name='payment',
            name='Status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
