# Generated by Django 5.0 on 2024-03-14 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0019_rename_total_order_price_alter_complain_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='From_Date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='To_Date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='complain',
            name='Status',
            field=models.CharField(choices=[('Unsolved', 'Unsolved'), ('Solved', 'Solved')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='Status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirm', 'Confirm')], max_length=25),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='Status',
            field=models.CharField(choices=[('Not Available', 'Not Available'), ('Available', 'Available')], max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='Status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=25),
        ),
    ]
