# Generated by Django 5.0 on 2024-03-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0021_remove_card_user_id_alter_complain_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='Status',
            field=models.CharField(choices=[('Unsolved', 'Unsolved'), ('Solved', 'Solved')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='Status',
            field=models.CharField(choices=[('Confirm', 'Confirm'), ('Pending', 'Pending')], max_length=25),
        ),
    ]
