# Generated by Django 5.0 on 2024-03-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0023_alter_order_status_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Payment_Method',
            field=models.CharField(choices=[('online', 'online'), ('offline', 'offline')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], max_length=20),
        ),
    ]
