# Generated by Django 5.0 on 2024-03-20 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0027_order_size_alter_complain_status_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='Product_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='newapp.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complain',
            name='Status',
            field=models.CharField(choices=[('Solved', 'Solved'), ('Unsolved', 'Unsolved')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='Status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirm', 'Confirm'), ('Cancelled', 'Cancelled')], max_length=25),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='Status',
            field=models.CharField(choices=[('Not Available', 'Not Available'), ('Available', 'Available')], max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='Status',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active')], max_length=25),
        ),
    ]
